name: publish check function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node v20.x environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: build
        shell: bash
        run: |
          npm install
          npm run build
          npm run test --if-present

      - name: deploy
        uses: Azure/functions-action@v1.5.2
        with:
          app-name: check
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
